spring.application.name=18_TRY_LIMHAI_PP_Spring_Homework002

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/my_hw_school
spring.datasource.username=postgres
spring.datasource.password=123
